site:
  title: Testing Angular
  start_page: docs-testing-angular::introduction.adoc
content:
  sources:
    - url: .
      branches: [HEAD]
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./ui-bundle
output:
  dir: ./docs